### ISSUE TITLE
Issues with your example

### ISSUE THREAD

**Issue by AdinhLux** [ketanchoyal/mapbox_search_flutter#14]
Hello, I'm encuntering issues when trying your library

In your example : https://pub.dev/packages/mapbox_search_flutter/example

- MapBoxStaticImage can't be defined
- There is Error messages in 'MapBoxPlaceSearchWidget'.

`Error: The getter 'country' isn't defined for the class 'MapBoxPlaceSearchWidget'.`
`Error: The getter 'location' isn't defined for the class 'MapBoxPlaceSearchWidget'.`

I've imported both libraries

  `mapbox_search_flutter: ^1.0.6`
  `mapbox_search: ^2.0.1+1`

**Comment by ketanchoyal** [comment]
Thanks @AdinhLux for reporting it, looks like I forgot to update the example app, I will do it asap

**Comment by gfsoluzioni** [comment]
Hi, I have installed your package in my flutter project, but I get the following errors:

/C:/flutter/.pub-cache/hosted/pub.dartlang.org/mapbox_search_flutter-1.0.6/lib/src/map_box_place_search_widget.dart:231:25: Error: The getter 'country' isn't defined for the class 'MapBoxPlaceSearchWidget'.
 - 'MapBoxPlaceSearchWidget' is from 'package: mapbox_search_flutter / mapbox_search_flutter.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/mapbox_search_flutter-1.0.6/lib/mapbox_search_flutter.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'country'.
        country: widget.country,
                        ^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/mapbox_search_flutter-1.0.6/lib/src/map_box_place_search_widget.dart:236:26: Error: The getter 'location' isn't defined for the class 'MapBoxPlaceSearchWidget'.
 - 'MapBoxPlaceSearchWidget' is from 'package: mapbox_search_flutter / mapbox_search_flutter.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/mapbox_search_flutter-1.0.6/lib/mapbox_search_flutter.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'location'.
        location: widget.location,
                         ^^^^^^^^

How can I solve? Thanks

**Comment by sagar440** [comment]
hello, i'm facing same issue. how can i solve it ?

**Comment by ketanchoyal** [comment]
@sagar440 @AdinhLux @gfsoluzioni sorry for the inconvenience I accidentally deleted some code and pushed it without testing, It should be working now as I have added it back
