### ISSUE TITLE
Font size grows too large in MapBoxPlaceSearchWidget

### ISSUE THREAD

**Issue by gseront** [ketanchoyal/mapbox_search_flutter#8]
The font size in this widget is dependent on the screen width as we can see in the following code. This cause the font to grow so large that its heigth overflows the edit text on web browsers.

Here is the code cause the problem:

`child: TextField(

              decoration: _inputStyle(),

              controller: _textEditingController,

              style: TextStyle(

                fontSize: MediaQuery.of(context).size.width * 0.04,

              ),`

Maybe set a maximum fontsize, or do not overwrite the Theme fontsize.

**Comment by ketanchoyal** [comment]
I'll update it asap, thanks for reporting

**Comment by ketanchoyal** [comment]
Done

**Comment by gseront** [comment]
Hi Ketan,
Hope you are well.
Thank you for the change you made to the MapBoxSearchWidget. I see the change on github, but the version on pub.dev of the 
mapbox_search_flutter lib has not been updated it still dates back june 12. Do you plan on publishing a new version with the change. I ask to be asble to keep my dependencies clean.
Best regards,


    Le samedi 3 octobre 2020 à 02:56:49 UTC+2, Ketan Choyal <notifications@github.com> a écrit :  
 
 


Done
